// Generated by ChatGPT
//
// Prompt 1: what is the simplest mmap use of V4L2 for raw data only
// Prompt 2: can you show me a non-blocking version
//
#include <errno.h>
#include <fcntl.h>
#include <linux/videodev2.h>
#include <poll.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <unistd.h>

#define BUFFER_COUNT 4
#define POLL_TIMEOUT_MS 1000

struct mapped_buffer {
    void *data;
    size_t length;
};

static int xioctl(int fd, unsigned long request, void *arg)
{
    int result;

    do {
        result = ioctl(fd, request, arg);
    } while (result == -1 && errno == EINTR);

    return result;
}

static void process_frame(const uint8_t *data,
                          size_t bytes_used,
                          unsigned width,
                          unsigned height,
                          unsigned stride,
                          uint32_t sequence)
{
    /*
     * For YUYV:
     *
     * byte 0: Y0
     * byte 1: U
     * byte 2: Y1
     * byte 3: V
     *
     * Complete processing before the buffer is requeued.
     */

    printf("frame=%u bytes=%zu size=%ux%u stride=%u\n",
           sequence, bytes_used, width, height, stride);

    (void)data;
}

int main(void)
{
    int fd = -1;
    int streaming = 0;
    struct mapped_buffer buffers[BUFFER_COUNT] = {0};
    unsigned buffer_count = 0;

    fd = open("/dev/video0", O_RDWR | O_NONBLOCK);
    if (fd == -1) {
        perror("open");
        return EXIT_FAILURE;
    }

    /*
     * Confirm that this node supports capture and streaming.
     */
    struct v4l2_capability capability = {0};

    if (xioctl(fd, VIDIOC_QUERYCAP, &capability) == -1) {
        perror("VIDIOC_QUERYCAP");
        goto cleanup;
    }

    uint32_t caps = capability.device_caps
                  ? capability.device_caps
                  : capability.capabilities;

    if (!(caps & V4L2_CAP_VIDEO_CAPTURE)) {
        fprintf(stderr, "Device does not support video capture\n");
        goto cleanup;
    }

    if (!(caps & V4L2_CAP_STREAMING)) {
        fprintf(stderr, "Device does not support streaming I/O\n");
        goto cleanup;
    }

    /*
     * Select uncompressed YUYV.
     */
    struct v4l2_format format = {0};

    format.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    format.fmt.pix.width = 640;
    format.fmt.pix.height = 480;
    format.fmt.pix.pixelformat = V4L2_PIX_FMT_YUYV;
    format.fmt.pix.field = V4L2_FIELD_ANY;

    if (xioctl(fd, VIDIOC_S_FMT, &format) == -1) {
        perror("VIDIOC_S_FMT");
        goto cleanup;
    }

    if (format.fmt.pix.pixelformat != V4L2_PIX_FMT_YUYV) {
        fprintf(stderr, "Camera did not accept YUYV\n");
        goto cleanup;
    }

    printf("Using %ux%u YUYV, stride=%u, sizeimage=%u\n",
           format.fmt.pix.width,
           format.fmt.pix.height,
           format.fmt.pix.bytesperline,
           format.fmt.pix.sizeimage);

    /*
     * Ask the driver for mmap buffers.
     */
    struct v4l2_requestbuffers request = {0};

    request.count = BUFFER_COUNT;
    request.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    request.memory = V4L2_MEMORY_MMAP;

    if (xioctl(fd, VIDIOC_REQBUFS, &request) == -1) {
        perror("VIDIOC_REQBUFS");
        goto cleanup;
    }

    if (request.count < 2) {
        fprintf(stderr, "Driver supplied too few buffers: %u\n",
                request.count);
        goto cleanup;
    }

    buffer_count = request.count;
    if (buffer_count > BUFFER_COUNT)
        buffer_count = BUFFER_COUNT;

    /*
     * Query and map each buffer.
     */
    for (unsigned i = 0; i < buffer_count; ++i) {
        struct v4l2_buffer buffer = {0};

        buffer.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
        buffer.memory = V4L2_MEMORY_MMAP;
        buffer.index = i;

        if (xioctl(fd, VIDIOC_QUERYBUF, &buffer) == -1) {
            perror("VIDIOC_QUERYBUF");
            goto cleanup;
        }

        buffers[i].length = buffer.length;
        buffers[i].data = mmap(NULL,
                               buffer.length,
                               PROT_READ | PROT_WRITE,
                               MAP_SHARED,
                               fd,
                               buffer.m.offset);

        if (buffers[i].data == MAP_FAILED) {
            buffers[i].data = NULL;
            perror("mmap");
            goto cleanup;
        }
    }

    /*
     * Queue every buffer before starting the stream.
     */
    for (unsigned i = 0; i < buffer_count; ++i) {
        struct v4l2_buffer buffer = {0};

        buffer.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
        buffer.memory = V4L2_MEMORY_MMAP;
        buffer.index = i;

        if (xioctl(fd, VIDIOC_QBUF, &buffer) == -1) {
            perror("VIDIOC_QBUF");
            goto cleanup;
        }
    }

    enum v4l2_buf_type type = V4L2_BUF_TYPE_VIDEO_CAPTURE;

    if (xioctl(fd, VIDIOC_STREAMON, &type) == -1) {
        perror("VIDIOC_STREAMON");
        goto cleanup;
    }

    streaming = 1;

    struct pollfd pfd = {
        .fd = fd,
        .events = POLLIN | POLLRDNORM
    };

    unsigned frames_processed = 0;

    while (frames_processed < 100) {
        /*
         * poll() waits only up to POLL_TIMEOUT_MS.
         * The program can do other work between calls.
         */
        int ready;

        do {
            ready = poll(&pfd, 1, POLL_TIMEOUT_MS);
        } while (ready == -1 && errno == EINTR);

        if (ready == -1) {
            perror("poll");
            break;
        }

        if (ready == 0) {
            printf("No frame available; doing other work\n");
            continue;
        }

        if (pfd.revents & (POLLERR | POLLHUP | POLLNVAL)) {
            fprintf(stderr, "poll error, revents=0x%x\n",
                    pfd.revents);
            break;
        }

        if (!(pfd.revents & (POLLIN | POLLRDNORM)))
            continue;

        /*
         * Drain every frame currently available.
         *
         * Because fd is nonblocking, DQBUF returns EAGAIN when
         * there are no more completed buffers.
         */
        for (;;) {
            struct v4l2_buffer buffer = {0};

            buffer.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
            buffer.memory = V4L2_MEMORY_MMAP;

            if (xioctl(fd, VIDIOC_DQBUF, &buffer) == -1) {
                if (errno == EAGAIN)
                    break;

                perror("VIDIOC_DQBUF");
                goto capture_done;
            }

            if (buffer.index >= buffer_count) {
                fprintf(stderr, "Invalid buffer index: %u\n",
                        buffer.index);
                goto capture_done;
            }

            process_frame(buffers[buffer.index].data,
                          buffer.bytesused,
                          format.fmt.pix.width,
                          format.fmt.pix.height,
                          format.fmt.pix.bytesperline,
                          buffer.sequence);

            if (xioctl(fd, VIDIOC_QBUF, &buffer) == -1) {
                perror("VIDIOC_QBUF");
                goto capture_done;
            }

            ++frames_processed;

            if (frames_processed >= 100)
                break;
        }
    }

capture_done:
    if (streaming) {
        if (xioctl(fd, VIDIOC_STREAMOFF, &type) == -1)
            perror("VIDIOC_STREAMOFF");

        streaming = 0;
    }

cleanup:
    if (streaming) {
        enum v4l2_buf_type cleanup_type =
            V4L2_BUF_TYPE_VIDEO_CAPTURE;

        xioctl(fd, VIDIOC_STREAMOFF, &cleanup_type);
    }

    for (unsigned i = 0; i < buffer_count; ++i) {
        if (buffers[i].data != NULL)
            munmap(buffers[i].data, buffers[i].length);
    }

    if (fd != -1)
        close(fd);

    return EXIT_SUCCESS;
}
