// This code was generated by ChatGPT with a query for the simplest code possible
// for an efficient MMAP implementation using double buffering only.
//
// Prompt: what is the simplest mmap use of V4L2 for raw data only
//
// The buffer can be expanded to allow for more elasticity in frame processing, but this allows for
// the UVC camera driver to use one of the two frames while the app uses the previously completed frame
// and is paced by how the app queues and dequeues the buffers.
//
// VIDIOC_QBUF and VIDIOC_DQBUF control buffering
//
#include <errno.h>
#include <fcntl.h>
#include <linux/videodev2.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <unistd.h>

#define BUFFER_COUNT 2

struct mapped_buffer {
    void   *data;
    size_t  length;
};

static int xioctl(int fd, unsigned long request, void *arg)
{
    int result;

    do {
        result = ioctl(fd, request, arg);
    } while (result == -1 && errno == EINTR);

    return result;
}

static void process_frame(const uint8_t *data,
                          size_t bytes_used,
                          unsigned width,
                          unsigned height,
                          unsigned bytes_per_line)
{
    /*
     * YUYV layout:
     *
     * data[0] = Y0
     * data[1] = U
     * data[2] = Y1
     * data[3] = V
     *
     * Each four-byte group represents two pixels.
     */

    printf("Frame: %zu bytes, %ux%u, stride %u\n",
           bytes_used, width, height, bytes_per_line);

    /*
     * Process data here.
     *
     * Do not assume bytes_per_line == width * 2.
     * The driver may add padding at the end of each row.
     */
}

int main(void)
{
    int fd = -1;
    struct mapped_buffer buffers[BUFFER_COUNT] = {0};
    unsigned buffer_count = 0;

    fd = open("/dev/video0", O_RDWR);
    if (fd == -1) {
        perror("open");
        return EXIT_FAILURE;
    }

    /*
     * 1. Select a raw, single-planar capture format.
     */
    struct v4l2_format format = {0};

    format.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    format.fmt.pix.width = 640;
    format.fmt.pix.height = 480;
    format.fmt.pix.pixelformat = V4L2_PIX_FMT_YUYV;
    format.fmt.pix.field = V4L2_FIELD_ANY;

    if (xioctl(fd, VIDIOC_S_FMT, &format) == -1) {
        perror("VIDIOC_S_FMT");
        goto cleanup;
    }

    if (format.fmt.pix.pixelformat != V4L2_PIX_FMT_YUYV) {
        fprintf(stderr, "Camera did not accept YUYV\n");
        goto cleanup;
    }

    printf("Using %ux%u YUYV, stride=%u, sizeimage=%u\n",
           format.fmt.pix.width,
           format.fmt.pix.height,
           format.fmt.pix.bytesperline,
           format.fmt.pix.sizeimage);

    /*
     * 2. Ask the driver to allocate mmap buffers.
     */
    struct v4l2_requestbuffers request = {0};

    request.count = BUFFER_COUNT;
    request.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
    request.memory = V4L2_MEMORY_MMAP;

    if (xioctl(fd, VIDIOC_REQBUFS, &request) == -1) {
        perror("VIDIOC_REQBUFS");
        goto cleanup;
    }

    if (request.count == 0 || request.count > BUFFER_COUNT) {
        fprintf(stderr, "Unexpected buffer count: %u\n", request.count);
        goto cleanup;
    }

    buffer_count = request.count;

    /*
     * 3. Query and map each driver buffer.
     */
    for (unsigned i = 0; i < buffer_count; ++i) {
        struct v4l2_buffer buffer = {0};

        buffer.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
        buffer.memory = V4L2_MEMORY_MMAP;
        buffer.index = i;

        if (xioctl(fd, VIDIOC_QUERYBUF, &buffer) == -1) {
            perror("VIDIOC_QUERYBUF");
            goto cleanup;
        }

        buffers[i].length = buffer.length;
        buffers[i].data = mmap(NULL,
                               buffer.length,
                               PROT_READ | PROT_WRITE,
                               MAP_SHARED,
                               fd,
                               buffer.m.offset);

        if (buffers[i].data == MAP_FAILED) {
            buffers[i].data = NULL;
            perror("mmap");
            goto cleanup;
        }
    }

    /*
     * 4. Give all buffers to the driver.
     */
    for (unsigned i = 0; i < buffer_count; ++i) {
        struct v4l2_buffer buffer = {0};

        buffer.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
        buffer.memory = V4L2_MEMORY_MMAP;
        buffer.index = i;

        if (xioctl(fd, VIDIOC_QBUF, &buffer) == -1) {
            perror("VIDIOC_QBUF");
            goto cleanup;
        }
    }

    /*
     * 5. Start capture.
     */
    enum v4l2_buf_type type = V4L2_BUF_TYPE_VIDEO_CAPTURE;

    if (xioctl(fd, VIDIOC_STREAMON, &type) == -1) {
        perror("VIDIOC_STREAMON");
        goto cleanup;
    }

    /*
     * 6. Blocking capture loop.
     *
     * Because the device was not opened with O_NONBLOCK,
     * VIDIOC_DQBUF waits until a completed frame is ready.
     */
    for (unsigned frame_number = 0; frame_number < 100; ++frame_number) {
        struct v4l2_buffer buffer = {0};

        buffer.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
        buffer.memory = V4L2_MEMORY_MMAP;

        if (xioctl(fd, VIDIOC_DQBUF, &buffer) == -1) {
            perror("VIDIOC_DQBUF");
            break;
        }

        if (buffer.index >= buffer_count) {
            fprintf(stderr, "Invalid buffer index\n");
            break;
        }

        process_frame(buffers[buffer.index].data,
                      buffer.bytesused,
                      format.fmt.pix.width,
                      format.fmt.pix.height,
                      format.fmt.pix.bytesperline);

        /*
         * The mapped frame remains valid until this buffer is
         * queued again. Finish processing before VIDIOC_QBUF.
         */
        if (xioctl(fd, VIDIOC_QBUF, &buffer) == -1) {
            perror("VIDIOC_QBUF");
            break;
        }
    }

    /*
     * 7. Stop capture.
     */
    if (xioctl(fd, VIDIOC_STREAMOFF, &type) == -1)
        perror("VIDIOC_STREAMOFF");

cleanup:
    for (unsigned i = 0; i < buffer_count; ++i) {
        if (buffers[i].data != NULL)
            munmap(buffers[i].data, buffers[i].length);
    }

    if (fd != -1)
        close(fd);

    return EXIT_SUCCESS;
}
